### ISSUE TITLE
Can't run on Windows

### ISSUE THREAD

**Issue by PierrunoYT** [majd/ipatool#189]
### What happened?

I can't run it on Windows. Can you please help me?

### Version

Latest

**Comment by majd** [comment]
Please provide more information and the issue you are having so that you can get a helpful answer.

If you are experiencing a specific error, please post the exact error message you are seeing. Additionally, run the tool in verbose mode to get as much output as possible.

**Comment by yolocat-dev** [comment]
```
panic: could not read metadata: failed to describe file 'C:\Users\samue\.ipatool': CreateFile C:\Users\samue\.ipatool: The system cannot find the file specified.

goroutine 1 [running]:
github.com/majd/ipatool/v2/pkg/util.Must[...]({0x0?, 0xbd76c0?}, {0xbd47c0?, 0xc000092300?})
        /Users/runner/work/ipatool/ipatool/pkg/util/must.go:6 +0x56
github.com/majd/ipatool/v2/cmd.initWithCommand(0xc000188600)
        /Users/runner/work/ipatool/ipatool/cmd/common.go:134 +0x3e5
github.com/majd/ipatool/v2/cmd.rootCmd.func1(0xc000188600, {0xaf66ce?, 0x1?, 0x1?})
        /Users/runner/work/ipatool/ipatool/cmd/root.go:31 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc000188600, {0xc000090130, 0x1, 0x1})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:896 +0x711
github.com/spf13/cobra.(*Command).ExecuteC(0xc000188000)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/majd/ipatool/v2/cmd.Execute()
        /Users/runner/work/ipatool/ipatool/cmd/root.go:54 +0x28
main.main()
        /Users/runner/work/ipatool/ipatool/main.go:10 +0x19
```

**Comment by yolocat-dev** [comment]
Seems to happen on macOS as well, fixed by simply creating it yourself: `mkdir C:\Users\name\.ipatool`

**Comment by majd** [comment]
@yolocat-dev That's a separate issue introduced in version 2.1.0. [Version 2.1.1](https://github.com/majd/ipatool/releases/tag/v2.1.1) fixes the issue.
