### ISSUE TITLE
Ubuntu 22.04 server (no desktop environment).

### ISSUE THREAD

**Issue by Geczy** [majd/ipatool#196]
I can reproduce this issue on Ubuntu 22.04 server (no desktop environment). 
I guess the application tried to use `keyring.SecretServiceBackend` as the backend, but since I don't have desktop environment install, it failed. 
I think there should be some fallback code.

_Originally posted by @kotori2 in https://github.com/majd/ipatool/issues/160#issuecomment-1518560100_

**Comment by Geczy** [comment]
i have this issue as well

```sh
panic: Specified keyring backend not available

goroutine 1 [running]:
github.com/majd/ipatool/v2/pkg/util.Must[...]({0x0?, 0x0?}, {0x54a680?, 0x40001046b0?})
	/Users/runner/work/ipatool/ipatool/pkg/util/must.go:6 +0x60
github.com/majd/ipatool/v2/cmd.newKeychain({0x54da60?, 0x400005ac60?}, {0x54da30?, 0x400001f180}, {0x476123, 0xe}, 0x1)
	/Users/runner/work/ipatool/ipatool/cmd/common.go:66 +0x1ac
github.com/majd/ipatool/v2/cmd.initWithCommand(0x40001e6600)
	/Users/runner/work/ipatool/ipatool/cmd/common.go:126 +0x388
github.com/majd/ipatool/v2/cmd.rootCmd.func1(0x40001e6600, {0x471cd4?, 0x4?, 0x4?})
	/Users/runner/work/ipatool/ipatool/cmd/root.go:31 +0xa8
github.com/spf13/cobra.(*Command).execute(0x40001e6600, {0x400007e940, 0x4, 0x4})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:896 +0x4f4
github.com/spf13/cobra.(*Command).ExecuteC(0x40001e6000)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/majd/ipatool/v2/cmd.Execute()
	/Users/runner/work/ipatool/ipatool/cmd/root.go:54 +0x28
main.main()
	/Users/runner/work/ipatool/ipatool/main.go:10 +0x1c
```
